# This rule is not used by the project fl-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ml.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: fl-operator
    app.kubernetes.io/managed-by: kustomize
  name: flexperiment-viewer-role
rules:
- apiGroups:
  - ml.example.com
  resources:
  - flexperiments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.example.com
  resources:
  - flexperiments/status
  verbs:
  - get
